# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/mkdocs/mkdocs.yml
# See: https://www.mkdocs.org/user-guide/configuration/

# TODO: Fill in all blank fields below.
site_name:
site_description:
site_url:

repo_name:
repo_url:
edit_uri: blob/main/docs/

copyright: Copyright 2021 ARDUINO SA (http://www.arduino.cc/)

theme:
  name: material
  logo: img/icon_mac_light.png
  palette:
    primary: teal
    accent: orange

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.magiclink:
      repo: contributor-guide
      repo_url_shorthand: true
      user: arduino
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  # TODO: Define navigation structure for all other source files.
